CREATE DATABASE SOMETHING; -- CREATE NEW DATABASE
SHOW DATABASES; -- SHOW ALL THE DATABASES
CREATE DATABASE IF NOT EXISTS FUNCTIONAL; -- IF THERE IS NO FUNCTIONAL DATABASE EXIST THEN CREATE THAT FUNCTION
SHOW DATABASES;
DROP DATABASE CLASSDB;
USE SOMETHING;
 